[build-system]
requires = ["setuptools", "Cython", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "pyemblite/_version.py"
versionfile_build = "pyemblite/_version.py"
tag_prefix = "v"
parentdir_prefix = "pyemblite-"
